require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewCityNotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # NewCityNotification. As you add validations to NewCityNotification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "city" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewCityNotificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all new_city_notifications as @new_city_notifications" do
      new_city_notification = NewCityNotification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:new_city_notifications).should eq([new_city_notification])
    end
  end

  describe "GET show" do
    it "assigns the requested new_city_notification as @new_city_notification" do
      new_city_notification = NewCityNotification.create! valid_attributes
      get :show, {:id => new_city_notification.to_param}, valid_session
      assigns(:new_city_notification).should eq(new_city_notification)
    end
  end

  describe "GET new" do
    it "assigns a new new_city_notification as @new_city_notification" do
      get :new, {}, valid_session
      assigns(:new_city_notification).should be_a_new(NewCityNotification)
    end
  end

  describe "GET edit" do
    it "assigns the requested new_city_notification as @new_city_notification" do
      new_city_notification = NewCityNotification.create! valid_attributes
      get :edit, {:id => new_city_notification.to_param}, valid_session
      assigns(:new_city_notification).should eq(new_city_notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NewCityNotification" do
        expect {
          post :create, {:new_city_notification => valid_attributes}, valid_session
        }.to change(NewCityNotification, :count).by(1)
      end

      it "assigns a newly created new_city_notification as @new_city_notification" do
        post :create, {:new_city_notification => valid_attributes}, valid_session
        assigns(:new_city_notification).should be_a(NewCityNotification)
        assigns(:new_city_notification).should be_persisted
      end

      it "redirects to the created new_city_notification" do
        post :create, {:new_city_notification => valid_attributes}, valid_session
        response.should redirect_to(NewCityNotification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved new_city_notification as @new_city_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewCityNotification.any_instance.stub(:save).and_return(false)
        post :create, {:new_city_notification => { "city" => "invalid value" }}, valid_session
        assigns(:new_city_notification).should be_a_new(NewCityNotification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewCityNotification.any_instance.stub(:save).and_return(false)
        post :create, {:new_city_notification => { "city" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested new_city_notification" do
        new_city_notification = NewCityNotification.create! valid_attributes
        # Assuming there are no other new_city_notifications in the database, this
        # specifies that the NewCityNotification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NewCityNotification.any_instance.should_receive(:update_attributes).with({ "city" => "MyString" })
        put :update, {:id => new_city_notification.to_param, :new_city_notification => { "city" => "MyString" }}, valid_session
      end

      it "assigns the requested new_city_notification as @new_city_notification" do
        new_city_notification = NewCityNotification.create! valid_attributes
        put :update, {:id => new_city_notification.to_param, :new_city_notification => valid_attributes}, valid_session
        assigns(:new_city_notification).should eq(new_city_notification)
      end

      it "redirects to the new_city_notification" do
        new_city_notification = NewCityNotification.create! valid_attributes
        put :update, {:id => new_city_notification.to_param, :new_city_notification => valid_attributes}, valid_session
        response.should redirect_to(new_city_notification)
      end
    end

    describe "with invalid params" do
      it "assigns the new_city_notification as @new_city_notification" do
        new_city_notification = NewCityNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewCityNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => new_city_notification.to_param, :new_city_notification => { "city" => "invalid value" }}, valid_session
        assigns(:new_city_notification).should eq(new_city_notification)
      end

      it "re-renders the 'edit' template" do
        new_city_notification = NewCityNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewCityNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => new_city_notification.to_param, :new_city_notification => { "city" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested new_city_notification" do
      new_city_notification = NewCityNotification.create! valid_attributes
      expect {
        delete :destroy, {:id => new_city_notification.to_param}, valid_session
      }.to change(NewCityNotification, :count).by(-1)
    end

    it "redirects to the new_city_notifications list" do
      new_city_notification = NewCityNotification.create! valid_attributes
      delete :destroy, {:id => new_city_notification.to_param}, valid_session
      response.should redirect_to(new_city_notifications_url)
    end
  end

end
